---
- name: Register systems with Red Hat
  hosts: all
  become: true

  tasks:

  - name: Register RHEL Subscription
    redhat_subscription:
      state: present
      username: "{{ rhel_user }}"
      password: "{{ rhel_pass }}"
      auto_attach: true

  - name: Enable 'Extras' Repo
    rhsm_repository:
      name: rhel-7-server-extras-rpms
      state: enabled

  - name: Enable 'Software Collections' Repo
    rhsm_repository:
      name: rhel-server-rhscl-7-rpms
      state: enabled

...

