---
- name: Register systems with Red Hat
  hosts: all
  become: true

  tasks:

  - name: Register RHEL Subscription
    redhat_subscription:
      state: present
      username: "{{ rhel_user }}"
      password: "{{ rhel_pass }}"
      auto_attach: true

  - name: Enable additional repositories
    rhsm_repository:
      name: "{{ item }}"
      state: enabled
    loop: "{{ repo_list }}"

...

