---
- name: Register systems with Red Hat
  hosts: all
  become: true
  vars_files:
    - vars/vars.yml
    - vars/vault.yml

  tasks:
  - name: Register RHEL Subscription
    community.general.redhat_subscription:
      state: present
      username: "{{ rhel_user }}"
      password: "{{ rhel_pass }}"
      auto_attach: true
...

