---
- name: Basic RHEL Configuration
  hosts: all
  become: yes
  vars_files:
    - vars/vars.yml
    - vars/vault.yml

  tasks:
  - name: Enable additional repositories
    community.general.rhsm_repository:
      name: "{{ item }}"
      state: enabled
    loop: "{{ repo_list }}"

  - name: Install Ansible
    ansible.builtin.dnf:
      name: ansible
      state: present
  
  - name: Set hostname
    ansible.builtin.hostname:
      name: "{{ rhel_hostname }}"
      use: systemd

  - name: Set Timezone to Eastern
    community.general.timezone:
      name: America/New_York

  - name: Restart Chronyd
    ansible.builtin.service:
      name: chronyd
      state: restart

