---
- name: Short Ansible Playbook for RHEL
  hosts: all
  become: true
  vars_files:
      - vars/main.yml


  tasks:

    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"

    - name: Start and enabled services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop: "{{ services }}"

    - name: Create index.html
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
      notify: restart web service

    - name: Ensure web server ports are open
      firewalld:
        service: "{{ item }}"
        immediate: true
        permanent: true
        state: enabled
      loop:
        - http
        - https


  handlers:

    - name: restart web service
      service:
        name: httpd
        state: restarted
...
