---
- name: Short Ansible Playbook for RHEL
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - vars/main.yml


  tasks:

  - name: Close http firewall ports
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: disabled
    loop:
      - http
      - https

  - name: Remove index.html
    file:
      path: /var/www/html/index.html
      state: absent
  
  - name: Stop services
    service:
      name: httpd
      state: stopped

  - name: Uninstall httpd
    yum:
      name: httpd
      state: absent

...

